---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: coder-github-app
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: google-secret-manager
  target:
    name: coder-github-app
    creationPolicy: Owner
  data:
    - secretKey: CODER_OAUTH2_GITHUB_CLIENT_ID
      remoteRef:
        key: coder-github-app-client-id
    - secretKey: CODER_OAUTH2_GITHUB_CLIENT_SECRET
      remoteRef:
        key: coder-github-app-client-secret
