apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: coder
  namespace: coder
spec:
  default:
    checkIntervalSec: 5
    config:
      httpHealthCheck:
        portSpecification: USE_SERVING_PORT
        requestPath: /healthz
      type: HTTP
    healthyThreshold: 1
    timeoutSec: 1
    unhealthyThreshold: 1
  targetRef:
    group: ""
    kind: Service
    name: coder
