apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: coder
  namespace: coder
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: coder
      app.kubernetes.io/name: coder
