---
# External secret for Coder DB password
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: coder-db-password
spec:
    refreshInterval: 1h # rate SecretManager pulls GCPSM
    secretStoreRef:
        kind: ClusterSecretStore
        name: google-secret-manager # name of the SecretStore (or kind specified)
    target:
        name: coder-db-password # name of the k8s Secret to be created
        creationPolicy: Owner
    data:
        - secretKey: DB_PASSWORD # The key within the Kubernetes secret to store the value within
          remoteRef:
              key: coder-postgres-password # The name of the GCPSM secret to refer to when creating the Kubernetes secret
