---
apiVersion: v2
name: abridge-coder
type: application
version: 0.1.0
dependencies:
  - name: coder
    version: 2.33.7
    repository: https://helm.coder.com/v2
  - name: coder-logstream-kube
    version: v0.0.15
    repository: https://helm.coder.com/logstream-kube
    condition: coder-logstream-kube.enabled
