# Development-specific overrides
---
coder:
  # Development-specific HTTPRoute configuration
  httpRoute:
    hostname: coder.abridge.coffee

  coder:
    # Development-specific configuration
    env:
      - name: DB_USER
        value: coder-app@client-dev-e301d.iam
      - name: CODER_ACCESS_URL
        value: https://coder.abridge.coffee

    # Development-specific service account
    serviceAccount:
      annotations:
        iam.gke.io/gcp-service-account: "coder-app@client-dev-e301d.iam.gserviceaccount.com"

    # Development-specific init container configuration
    initContainers:
      - name: cloud-sql-proxy
        args:
          - client-dev-e301d:us-central1:coder-postgres-db
